name = "Tenet"
uuid = "85d41934-b9cd-44e1-8730-56d86f15f3ec"
authors = ["Sergio Sánchez Ramírez <sergio.sanchez.ramirez@bsc.es>"]
version = "0.1.0"

[deps]
ReusePatterns = "a39b5e78-89b5-562b-97d8-70689129df0c"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
WhereTraits = "c9d4e05b-6318-49cb-9b56-e0e2b0ceadd8"

[compat]
julia = "1.6"
