name: Tenet benchmarks with BenchmarkTools.jl
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run tenet benchmark
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: runner.os−test−env.cache−name−{{ hashFiles('**/Project.toml') }}
          restore-keys: |
            runner.os−test−
            ${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Run benchmark
        run: |
          cd benchmarks
          julia --project --color=yes -e '
            using Pkg;
            #Pkg.Registry.add(url = "https://github.com/bsc-quantic/Registry");
            pkg"registry add https://github.com/bsc-quantic/Registry.git";
            pkg"registry add General";
            Pkg.instantiate();
            pkg"add Tenet#master";
            include("bench1.jl")'

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: tenet benchmark result
          tool: 'julia'
          output-file-path: benchmarks/output.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          #alert-threshold: '200%'
          #comment-on-alert: true
          #fail-on-alert: true
          #alert-comment-cc-users: '@ktrz,@findmyway'
