name: "[CI] Generate sysimage"
on:
  workflow_dispatch:
concurrency:
jobs:
  generate:
    name: Julia ${{ matrix.version }} - ${{ matrix.arch }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.8'
          - '1.9'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          include-all-prereleases: true
      - name: Add Julia registries
        run: |
          using Pkg
          pkg"registry add https://github.com/bsc-quantic/Registry.git"
          pkg"registry add General"
        shell: julia {0}
      - name: Generate sysimage
        run: |
          using Pkg
          pkg"add PackageCompiler"
          pkg"add CairoMakie"
          using PackageCompiler
          create_sysimage(["Makie","GraphMakie","CairoMakie"]; sysimage_path="test_sysimage.so")
        shell: julia {0}
      - uses: actions/upload-artifact@v3
        with:
          name: test_sysimage-${{ matrix.version }}-${{ matrix.arch }}-${{ matrix.os }}
          path: test_sysimage.so
              