name: "[CI] Generate sysimage"
on:
  workflow_dispatch:
jobs:
  generate:
    name: Julia ${{ matrix.version }} - ${{ matrix.arch }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.8'
          - '1.9'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
          include-all-prereleases: true
      - name: Add Julia registries
        run: |
          using Pkg
          pkg"registry add https://github.com/bsc-quantic/Registry.git"
          pkg"registry add General"
        shell: julia {0}
      - name: Generate sysimage
        run: |
          using Pkg
          using Logging

          project = Pkg.project()
          deps = project.dependencies |> keys |> collect

          weakdeps = if isdefined(Base, :get_extension)
              vcat(vcat.(Pkg.Types.read_project(project.path).weakdeps |> keys |> collect)...)
            else
              []
            end

          # get test dependencies
          testdeps = begin
            Pkg.activate("test")
            testdeps = Pkg.project().dependencies |> keys |> collect
            filter(∉(["Aqua", "Test", "ChainRulesTestUtils"]), testdeps)
          end

          @info "Dependencies" direct = join(deps, ", ") weakdeps = join(weakdeps, ", ") test = join(testdeps, ", ")

          Pkg.activate(; temp=true)
          deps = unique(vcat(deps, weakdeps, testdeps))
          Pkg.add(vcat(["PackageCompiler"], deps))

          # NOTE filter CairoMakie because it crashes on sysimage generation
          filter!(!=("CairoMakie"), deps)

          # generate sysimage
          using PackageCompiler

          create_sysimage(deps; sysimage_path="test_sysimage.so")
        shell: julia --project=@. --color=yes {0}
      - uses: actions/cache/save@v3
        with:
          path: test_sysimage.so
          key: sysimage-${{ matrix.version }}-${{ matrix.arch }}-${{ matrix.os }}
